# 语法就是 “列名: DuckDB 类型”
# 只写一次即可，所有表共用

"其中：房屋和构筑物264;本年": DECIMAL(18,2)
"经营性单位收入":  DECIMAL(18,2)
"非经营性单位支出 （费用）": DECIMAL(18,2)
"统一社会信用代码": TEXT
"单位详细名称":   TEXT
"数据来源":      TEXT
"是否一套表单位": BOOLEAN
"行业代码":      TEXT
"专业分类":      TEXT